### PR TITLE
Iframe sandboxing and therePerfect

### PR DESCRIPTION
**Pull request by jswartwood**
Adding iframe sandboxing to allow multiple scripts to be evaluated simultaneously.

Adding therePerfect method to return the "working" scripts; now you can recommit and go home for the day.

### CODE REVIEW

**Comment by mattdiamond** [comment]
This is an awesome idea... I'll merge it in once I have some more time to look it over.

**Comment by wjcrowcroft** [comment]
+1

This is the main feature I'm waiting on before we incorporate this into our build process at work.

**Comment by matthopson** [comment]
... they should have sent a poet.

**Comment by jswartwood** [comment]
I was thinking about this today, and with my pull we lose execution in the main frame which will cut potentially working jQuery code because the expected DOM is missing.

Also, the execution will no longer be "visible" for those that still want to FuckIt directly in production (vs using FuckIt as part of their build process).

This pull may need some tweaks... maybe clone the parent DOM into the iframe first before running, then possibly capture the `therePerfect` output and dump it back into the main thread for "visible" execution.

**Comment by mattdiamond** [comment]
What if we return a Deferred object that resolves once the eval goes through, allowing the developer to chain FuckIt calls?

I suppose we lose the advantage of asynchronous script loading...

**Comment by jswartwood** [comment]
Simple. I like it.

**Comment by mattdiamond** [comment]
done and done.

**Comment by jswartwood** [comment]
How do you feel about `therePerfect`? I can easily mod it to work with the deferreds instead of iframes.

**Comment by mattdiamond** [comment]
I'm conflicted... on the one hand, I like the idea of returning the "fixed" scripts, but on the other hand, that would inspire people to actually fix their mistakes instead of relying on a terribly designed and ultimately harmful crutch. Lame.

What about resolving the Deferred with the corrected script so it's available in the callback? Like so:

```
FuckIt("badScript.js").done(function(fixedScript){
    console.log(fixedScript); //hooray
});
```

We would just need to include window.fuckedScript as the sole argument to the .resolve() call.

**Comment by jswartwood** [comment]
My thought was that a sarcastic name might be enough to disuade people from actually using output in the real world - it could've just as easily been called `lessFuckedScript` or `atLeastItsSomething`. If we just return the "clean" output, there may be even less implication about the completely horrible idea of actually using anything this lib spits out.

Honestly, I can't imagine anyone actually assuming this is doing anything useful... the fact that the script gets run over-and-over until it's fixed should probably cause enough issues itself.

I did kind of want to ride the build-tools wave a bit... would a phantomjs headless runner (with "clean script" export) be too much? :P

**Comment by mattdiamond** [comment]
Oh yeah I'm totally on the same page, I would hope nobody actually uses this for any real purpose. Though the amount of people that have joked about using it in production makes me worry a little.

I like the build-tool idea though... I think that would be a better place for actually retrieving and saving the processed scripts, rather than the browser plugin. Feel free to write something up for that. Hell, someone should probably build a node-fuckit package.

Also, I'm pretty sure when it comes to FuckItJS, there's no such thing as "too much."

**Comment by jswartwood** [comment]
I would also say there is almost certainly no such thing as "too little" ;)

**Pull request closed without merging**
